### PR TITLE
Add python scripts to generate configuration files from templates

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
This PR adds exact duplicates of scripts in GDASApp to generate YAML and JSON files from templates using wxflow.

Eventually, the aforementioned scripts will be removed from GDASApp and kept here for usage by all EMC NWP applications.

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
Decided to add a brief README to the front page also

**Review by RussTreadon-NOAA — COMMENTED** [review]
Seems OK.   Have we / how do we test the scripts to ensure they work as intended?

**Comment by CoryMartin-NOAA** [comment]
Good question. How much automated testing do we want to try to build in this repo? We can pretty easily have it download BUFR files from NOMADS and try to convert. 

In the short term, one just needs python and wxflow in your environment and run the scripts. We don't yet have the templates in this repo because I don't want to do them all in one PR, but rather break them into pieces so we can ensure consistency with formatting, filenames, etc.

**Review by RussTreadon-NOAA — APPROVED** [review]

**Review by emilyhcliu — APPROVED** [review]

**Comment by emilyhcliu** [comment]
> Good question. How much automated testing do we want to try to build in this repo? We can pretty easily have it download BUFR files from NOMADS and try to convert.
> 
> In the short term, one just needs python and wxflow in your environment and run the scripts. We don't yet have the templates in this repo because I don't want to do them all in one PR, but rather break them into pieces so we can ensure consistency with formatting, filenames, etc.

@CoryMartin-NOAA Are NOMADS BUFR files available as soon as the BUFR files are in the Dump?

**Comment by emilyhcliu** [comment]
> > Good question. How much automated testing do we want to try to build in this repo? We can pretty easily have it download BUFR files from NOMADS and try to convert.
> > In the short term, one just needs python and wxflow in your environment and run the scripts. We don't yet have the templates in this repo because I don't want to do them all in one PR, but rather break them into pieces so we can ensure consistency with formatting, filenames, etc.
> 
> @CoryMartin-NOAA Are NOMADS BUFR files available as soon as the BUFR files are in the Dump?

I just checked [NOMADS](https://nomads.ncep.noaa.gov/) and saw that NOMADS does have files from operational ObsProc processing.

**Comment by CoryMartin-NOAA** [comment]
Approximately, yes, probably within minutes. https://nomads.ncep.noaa.gov/pub/data/nccf/com/obsproc/prod/gdas.20240429/

**Pull request merged**
